/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  DateOffset,
  EventDimension,
} from './components/schedule-day-board/schedule-day-board';
import {
  ScheduleResource,
} from './view/ScheduleResource';


export namespace Components {

  interface ScheduleDayBoard {
    'getDateOffset': (time: string) => DateOffset;
    'getEventDimensions': (from: string, to: string) => EventDimension;
    'getTimeLineWidth': () => number;
    'isReady': boolean;
    'range': String;
    'step': Number;
  }
  interface ScheduleDayBoardAttributes extends StencilHTMLAttributes {
    'isReady'?: boolean;
    'onReady'?: (event: CustomEvent) => void;
    'range'?: String;
    'step'?: Number;
  }

  interface ScheduleDay {
    'resources': Array<ScheduleResource>;
  }
  interface ScheduleDayAttributes extends StencilHTMLAttributes {
    'resources'?: Array<ScheduleResource>;
  }

  interface ScheduleDayEvent {
    'from': string;
    'to': string;
  }
  interface ScheduleDayEventAttributes extends StencilHTMLAttributes {
    'from'?: string;
    'to'?: string;
  }

  interface ScheduleResource {}
  interface ScheduleResourceAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'ScheduleDayBoard': Components.ScheduleDayBoard;
    'ScheduleDay': Components.ScheduleDay;
    'ScheduleDayEvent': Components.ScheduleDayEvent;
    'ScheduleResource': Components.ScheduleResource;
  }

  interface StencilIntrinsicElements {
    'schedule-day-board': Components.ScheduleDayBoardAttributes;
    'schedule-day': Components.ScheduleDayAttributes;
    'schedule-day-event': Components.ScheduleDayEventAttributes;
    'schedule-resource': Components.ScheduleResourceAttributes;
  }


  interface HTMLScheduleDayBoardElement extends Components.ScheduleDayBoard, HTMLStencilElement {}
  var HTMLScheduleDayBoardElement: {
    prototype: HTMLScheduleDayBoardElement;
    new (): HTMLScheduleDayBoardElement;
  };

  interface HTMLScheduleDayElement extends Components.ScheduleDay, HTMLStencilElement {}
  var HTMLScheduleDayElement: {
    prototype: HTMLScheduleDayElement;
    new (): HTMLScheduleDayElement;
  };

  interface HTMLScheduleDayEventElement extends Components.ScheduleDayEvent, HTMLStencilElement {}
  var HTMLScheduleDayEventElement: {
    prototype: HTMLScheduleDayEventElement;
    new (): HTMLScheduleDayEventElement;
  };

  interface HTMLScheduleResourceElement extends Components.ScheduleResource, HTMLStencilElement {}
  var HTMLScheduleResourceElement: {
    prototype: HTMLScheduleResourceElement;
    new (): HTMLScheduleResourceElement;
  };

  interface HTMLElementTagNameMap {
    'schedule-day-board': HTMLScheduleDayBoardElement
    'schedule-day': HTMLScheduleDayElement
    'schedule-day-event': HTMLScheduleDayEventElement
    'schedule-resource': HTMLScheduleResourceElement
  }

  interface ElementTagNameMap {
    'schedule-day-board': HTMLScheduleDayBoardElement;
    'schedule-day': HTMLScheduleDayElement;
    'schedule-day-event': HTMLScheduleDayEventElement;
    'schedule-resource': HTMLScheduleResourceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
