/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  DateOffset,
  EventDimension,
} from './components/schedule-day-board/schedule-day-board';
import {
  ScheduleResource,
} from './view/ScheduleResource';
import {
  DateOffset as DateOffset2,
  EventDimension as EventDimension2,
} from './components/timeline-component/timeline-component';
import {
  ScheduleEvent,
} from './view/ScheduleEvent';


export namespace Components {

  interface ScheduleDayBoard {
    'getDateOffset': (time: string) => DateOffset;
    'getEventDimensions': (from: string, to: string) => EventDimension;
    'getTimeLineWidth': () => number;
    'isReady': boolean;
    'range': String;
    'step': Number;
  }
  interface ScheduleDayBoardAttributes extends StencilHTMLAttributes {
    'isReady'?: boolean;
    'onReady'?: (event: CustomEvent) => void;
    'range'?: String;
    'step'?: Number;
  }

  interface ScheduleDay {
    'resources': Array<ScheduleResource>;
  }
  interface ScheduleDayAttributes extends StencilHTMLAttributes {
    'resources'?: Array<ScheduleResource>;
  }

  interface ScheduleDayEvent {
    'from': string;
    'to': string;
  }
  interface ScheduleDayEventAttributes extends StencilHTMLAttributes {
    'from'?: string;
    'to'?: string;
  }

  interface ScheduleResource {}
  interface ScheduleResourceAttributes extends StencilHTMLAttributes {}

  interface ScheduleTimeline {
    'getDateOffset': (date: Date) => DateOffset;
    'getEventDimensions': (event: ScheduleEvent) => EventDimension;
    'getWidth': () => string;
    'range': String;
  }
  interface ScheduleTimelineAttributes extends StencilHTMLAttributes {
    'range'?: String;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ScheduleDayBoard': Components.ScheduleDayBoard;
    'ScheduleDay': Components.ScheduleDay;
    'ScheduleDayEvent': Components.ScheduleDayEvent;
    'ScheduleResource': Components.ScheduleResource;
    'ScheduleTimeline': Components.ScheduleTimeline;
  }

  interface StencilIntrinsicElements {
    'schedule-day-board': Components.ScheduleDayBoardAttributes;
    'schedule-day': Components.ScheduleDayAttributes;
    'schedule-day-event': Components.ScheduleDayEventAttributes;
    'schedule-resource': Components.ScheduleResourceAttributes;
    'schedule-timeline': Components.ScheduleTimelineAttributes;
  }


  interface HTMLScheduleDayBoardElement extends Components.ScheduleDayBoard, HTMLStencilElement {}
  var HTMLScheduleDayBoardElement: {
    prototype: HTMLScheduleDayBoardElement;
    new (): HTMLScheduleDayBoardElement;
  };

  interface HTMLScheduleDayElement extends Components.ScheduleDay, HTMLStencilElement {}
  var HTMLScheduleDayElement: {
    prototype: HTMLScheduleDayElement;
    new (): HTMLScheduleDayElement;
  };

  interface HTMLScheduleDayEventElement extends Components.ScheduleDayEvent, HTMLStencilElement {}
  var HTMLScheduleDayEventElement: {
    prototype: HTMLScheduleDayEventElement;
    new (): HTMLScheduleDayEventElement;
  };

  interface HTMLScheduleResourceElement extends Components.ScheduleResource, HTMLStencilElement {}
  var HTMLScheduleResourceElement: {
    prototype: HTMLScheduleResourceElement;
    new (): HTMLScheduleResourceElement;
  };

  interface HTMLScheduleTimelineElement extends Components.ScheduleTimeline, HTMLStencilElement {}
  var HTMLScheduleTimelineElement: {
    prototype: HTMLScheduleTimelineElement;
    new (): HTMLScheduleTimelineElement;
  };

  interface HTMLElementTagNameMap {
    'schedule-day-board': HTMLScheduleDayBoardElement
    'schedule-day': HTMLScheduleDayElement
    'schedule-day-event': HTMLScheduleDayEventElement
    'schedule-resource': HTMLScheduleResourceElement
    'schedule-timeline': HTMLScheduleTimelineElement
  }

  interface ElementTagNameMap {
    'schedule-day-board': HTMLScheduleDayBoardElement;
    'schedule-day': HTMLScheduleDayElement;
    'schedule-day-event': HTMLScheduleDayEventElement;
    'schedule-resource': HTMLScheduleResourceElement;
    'schedule-timeline': HTMLScheduleTimelineElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
